version: '3'
services:

  dbservice:
    container_name: mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD = root
    
    volumes:
      - C:\Users\Jyoti\OneDrive\Desktop\ashish-test\new_demo\employee-service\employee-service\data
    
      
  appservice:
    build: ashishiitk/employee-service
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url = jdbc:mysql://dbservice:3306/ashish_demo
      - spring.datasource.username = root
      - spring.datasource.password = root    
    
    
      

      
