version: '3'
services:

  dbservice:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root      
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - myapp
  
  registry-service:
    image: registry-server
    networks:
      - myapp 
    ports: 
      - "8761:8761"
           
  employee-service:
    image: employee-service:latest
    depends_on:
      - dbservice
      - registry-service
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/ashish_demo?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root 
    ports:
      - 9086:9086
    networks:
      - myapp
      
networks:
   myapp:  
    
    
      

      
