server:
  port: 9086

spring:
  application:
    name: EMPLOYEE-SERVICE
    
  datasource:
    url: jdbc:mysql://localhost:3306/ashish_demo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver  

  config:
    import: configserver:http://localhost:9084    
       
